# Generated by Django 5.2.14 on 2026-05-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="allowed_tags",
            field=models.CharField(
                blank=True,
                help_text="쉼표로 구분. 예: 공지,질문,건의,회의록",
                max_length=200,
                verbose_name="허용 말머리",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="board_type",
            field=models.CharField(
                choices=[
                    ("notice", "공지사항"),
                    ("free", "자유게시판"),
                    ("volunteer", "봉사활동"),
                    ("archive", "지킴이 아카이브"),
                    ("event", "행사/모임"),
                    ("suggestion", "건의/소통"),
                    ("gallery", "갤러리"),
                    ("trade", "나눔/장터"),
                    ("qna", "Q&A"),
                ],
                default="free",
                max_length=20,
                verbose_name="유형",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="write_permission",
            field=models.CharField(
                choices=[
                    ("all", "전체"),
                    ("member", "회원"),
                    ("staff", "운영진"),
                    ("admin", "관리자"),
                ],
                default="all",
                help_text="all/member/staff/admin",
                max_length=20,
                verbose_name="쓰기권한",
            ),
        ),
    ]
