# Generated by Django 5.2.14 on 2026-05-22 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_board_allowed_tags_alter_board_board_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="가격"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "판매중/나눔중"),
                            ("reserved", "예약중"),
                            ("sold", "판매완료"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="KRW", max_length=10, verbose_name="통화"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade",
                        to="core.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래 정보",
                "verbose_name_plural": "거래 정보 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
