# Generated by Django 5.2.14 on 2026-05-23 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_trade"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="등급명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="순서 (낮을수록 하위)"
                    ),
                ),
                (
                    "badge_color",
                    models.CharField(
                        choices=[
                            ("secondary", "회색 (기본)"),
                            ("primary", "파랑"),
                            ("success", "초록"),
                            ("info", "하늘"),
                            ("warning", "노랑"),
                            ("danger", "빨강"),
                            ("dark", "검정"),
                        ],
                        default="secondary",
                        max_length=20,
                        verbose_name="배지 색상",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-user",
                        help_text="FontAwesome 클래스명",
                        max_length=50,
                        verbose_name="아이콘 클래스",
                    ),
                ),
                (
                    "auto_upgrade",
                    models.BooleanField(default=False, verbose_name="자동 등업 여부"),
                ),
                (
                    "required_activities",
                    models.PositiveIntegerField(
                        default=0, verbose_name="필요 봉사 횟수"
                    ),
                ),
                (
                    "required_points",
                    models.PositiveIntegerField(default=0, verbose_name="필요 포인트"),
                ),
                (
                    "can_read_all",
                    models.BooleanField(
                        default=True,
                        help_text="상위 등급이 하위 등급 게시물 열람 가능",
                        verbose_name="전체 게시물 열람",
                    ),
                ),
                (
                    "can_write",
                    models.BooleanField(default=True, verbose_name="글쓰기 가능"),
                ),
                (
                    "can_comment",
                    models.BooleanField(default=True, verbose_name="댓글 가능"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="사용중")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "회원 등급",
                "verbose_name_plural": "회원 등급 목록",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BoardGradePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_read",
                    models.BooleanField(default=True, verbose_name="열람 가능"),
                ),
                (
                    "can_write",
                    models.BooleanField(default=False, verbose_name="글쓰기 가능"),
                ),
                (
                    "can_comment",
                    models.BooleanField(default=True, verbose_name="댓글 가능"),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_permissions",
                        to="core.board",
                        verbose_name="게시판",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_permissions",
                        to="core.membergrade",
                        verbose_name="등급",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시판 등급 권한",
                "verbose_name_plural": "게시판 등급 권한 목록",
                "unique_together": {("board", "grade")},
            },
        ),
    ]
