# Generated by Django 5.2.14 on 2026-05-25 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_membergrade_boardgradepermission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activityverification",
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="choice",
            options={},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
        migrations.AlterModelOptions(
            name="poll",
            options={},
        ),
        migrations.AlterModelOptions(
            name="trade",
            options={},
        ),
        migrations.RemoveField(
            model_name="choice",
            name="label",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="order",
        ),
        migrations.RemoveField(
            model_name="event",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="title",
        ),
        migrations.RemoveField(
            model_name="event",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="choice",
            name="text",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="poll",
            name="votes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="activityproof",
            name="proof_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="activity_proofs/"
            ),
        ),
        migrations.AlterField(
            model_name="activityverification",
            name="activity_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activityverification",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activityverification",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activityverification",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="activityverification",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="board",
            name="allowed_tags",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="board",
            name="board_type",
            field=models.CharField(
                choices=[
                    ("notice", "공지사항"),
                    ("free", "자유게시판"),
                    ("volunteer", "봉사활동"),
                    ("archive", "지킴이 아카이브"),
                    ("event", "행사/모임"),
                    ("suggestion", "건의/소통"),
                    ("gallery", "갤러리"),
                    ("trade", "나눔/장터"),
                    ("qna", "Q&A"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="board",
            name="icon",
            field=models.CharField(default="fas fa-clipboard", max_length=50),
        ),
        migrations.AlterField(
            model_name="board",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="board",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="board",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="board",
            name="write_permission",
            field=models.CharField(
                choices=[
                    ("all", "전체"),
                    ("member", "회원"),
                    ("staff", "운영진"),
                    ("admin", "관리자"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="boardgradepermission",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_permissions",
                to="core.board",
            ),
        ),
        migrations.AlterField(
            model_name="boardgradepermission",
            name="can_comment",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="boardgradepermission",
            name="can_read",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="boardgradepermission",
            name="can_write",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="boardgradepermission",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_permissions",
                to="core.membergrade",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="choice",
            name="votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="unit_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event",
                to="core.post",
            ),
        ),
        migrations.AlterField(
            model_name="meetup",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="membergrade",
            name="auto_upgrade",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="membergrade",
            name="badge_color",
            field=models.CharField(
                choices=[
                    ("secondary", "회색"),
                    ("primary", "파랑"),
                    ("success", "초록"),
                    ("info", "하늘"),
                    ("warning", "노랑"),
                    ("danger", "빨강"),
                    ("dark", "검정"),
                ],
                default="secondary",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="membergrade",
            name="can_comment",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="membergrade",
            name="can_read_all",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="membergrade",
            name="can_write",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="membergrade",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="membergrade",
            name="icon",
            field=models.CharField(default="fas fa-user", max_length=50),
        ),
        migrations.AlterField(
            model_name="membergrade",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="membergrade",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="membergrade",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="membergrade",
            name="required_activities",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="membergrade",
            name="required_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="poll",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="poll",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polls",
                to="core.post",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="question",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="core.board",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="core.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(upload_to="posts/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="trade",
            name="currency",
            field=models.CharField(default="KRW", max_length=10),
        ),
        migrations.AlterField(
            model_name="trade",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trade",
                to="core.post",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "판매중/나눔중"),
                    ("reserved", "예약중"),
                    ("sold", "판매완료"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table=None,
        ),
    ]
