# Generated by Django 5.2.14 on 2026-05-29 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_activityverification_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["activity_type", "name"],
                "verbose_name": "봉사 활동",
                "verbose_name_plural": "봉사 활동 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="activityproof",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "활동 인증",
                "verbose_name_plural": "활동 인증 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "소그룹",
                "verbose_name_plural": "소그룹 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="managementdocument",
            options={
                "ordering": ["category", "title"],
                "verbose_name": "관리 문서",
                "verbose_name_plural": "관리 문서 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="meetup",
            options={
                "ordering": ["scheduled_at"],
                "verbose_name": "번개/모임",
                "verbose_name_plural": "번개/모임 목록",
            },
        ),
        migrations.AlterField(
            model_name="managementdocument",
            name="category",
            field=models.CharField(max_length=50, verbose_name="카테고리"),
        ),
        migrations.AlterField(
            model_name="managementdocument",
            name="content",
            field=models.TextField(verbose_name="내용"),
        ),
        migrations.AlterField(
            model_name="managementdocument",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
        ),
        migrations.AlterField(
            model_name="managementdocument",
            name="embeddings",
            field=models.JSONField(blank=True, null=True, verbose_name="임베딩"),
        ),
        migrations.AlterField(
            model_name="managementdocument",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성화"),
        ),
        migrations.AlterField(
            model_name="managementdocument",
            name="title",
            field=models.CharField(max_length=200, verbose_name="제목"),
        ),
        migrations.AlterField(
            model_name="managementdocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="dm/")),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "1:1 메시지",
                "verbose_name_plural": "1:1 메시지 목록",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="public_chat/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "오픈채팅",
                "verbose_name_plural": "오픈채팅 목록",
                "ordering": ["created_at"],
            },
        ),
    ]
