# Generated by Django 5.2.14 on 2026-05-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_activity_options_alter_activityproof_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="groupchat",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="groupchat",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="groupchat",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
