# Generated by Django 5.2.14 on 2026-05-29 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_directmessage_is_active_groupchat_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicchat",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="publicchat",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="설문 제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "survey_type",
                    models.CharField(
                        choices=[
                            ("single", "단일 선택"),
                            ("multiple", "복수 선택"),
                            ("text", "주관식"),
                            ("rating", "평점 (1-5점)"),
                        ],
                        default="single",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "작성중"),
                            ("active", "진행중"),
                            ("closed", "마감"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=True, verbose_name="익명 응답"),
                ),
                (
                    "allow_multiple",
                    models.BooleanField(default=False, verbose_name="중복 응답 허용"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="마감일"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "설문조사",
                "verbose_name_plural": "설문조사 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300, verbose_name="질문")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "단일 선택"),
                            ("multiple", "복수 선택"),
                            ("text", "주관식"),
                            ("rating", "평점"),
                        ],
                        default="single",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                (
                    "options",
                    models.JSONField(blank=True, default=list, verbose_name="선택지"),
                ),
                ("is_required", models.BooleanField(default=True, verbose_name="필수")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "설문 질문",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", models.JSONField(default=dict, verbose_name="응답")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "respondent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="core.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "설문 응답",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
