# Generated by Django 5.2.14 on 2026-05-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_publicchat_is_active_publicchat_is_pinned_survey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="description",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="질문 설명"
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="rows",
            field=models.JSONField(
                blank=True, default=list, verbose_name="행 (매트릭스용)"
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="scale_max",
            field=models.IntegerField(default=10, verbose_name="최댓값"),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="scale_max_label",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="최댓값 레이블"
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="scale_min",
            field=models.IntegerField(default=1, verbose_name="최솟값"),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="scale_min_label",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="최솟값 레이블"
            ),
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single", "단일 선택"),
                    ("multiple", "복수 선택"),
                    ("text", "주관식"),
                    ("rating", "평점 (1-5점)"),
                    ("scale", "선형 척도 (슬라이더)"),
                    ("date", "날짜 선택"),
                    ("daterange", "날짜 범위 선택"),
                    ("rank", "순위 매기기"),
                    ("matrix", "매트릭스/표"),
                    ("section", "섹션 구분"),
                ],
                default="single",
                max_length=20,
                verbose_name="유형",
            ),
        ),
    ]
