# Generated by Django 5.2.14 on 2026-05-29 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_surveyquestion_description_surveyquestion_rows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="related_posts",
            field=models.ManyToManyField(
                blank=True, to="core.post", verbose_name="관련 게시글"
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="source_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surveys",
                to="core.post",
                verbose_name="원본 게시글",
            ),
        ),
    ]
