# Generated by Django 5.2.14 on 2026-05-29 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_post_related_posts_survey_source_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="linked_survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_posts",
                to="core.survey",
                verbose_name="삽입 설문",
            ),
        ),
    ]
