# Generated by Django 5.2.14 on 2026-05-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_post_linked_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=30, verbose_name="닉네임"),
        ),
    ]
