# Generated by Django 5.2.14 on 2026-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_customuser_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dong",
            field=models.CharField(blank=True, max_length=10, verbose_name="동"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ho",
            field=models.CharField(blank=True, max_length=10, verbose_name="호"),
        ),
    ]
