# Generated by Django 5.2.14 on 2026-05-29 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_customuser_dong_customuser_ho"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatPoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_type", models.CharField(default="public", max_length=20)),
                ("question", models.CharField(max_length=200, verbose_name="질문")),
                ("options", models.JSONField(default=list, verbose_name="선택지")),
                ("votes", models.JSONField(default=dict, verbose_name="투표 결과")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="core.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 투표",
                "ordering": ["-created_at"],
            },
        ),
    ]
