# Generated by Django 5.2.14 on 2026-05-29 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_chatpoll"),
    ]

    operations = [
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                ("is_read", models.BooleanField(default=False)),
                ("sender_deleted", models.BooleanField(default=False)),
                ("receiver_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="core.letter",
                        verbose_name="원본 쪽지",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="받는 사람",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="보낸 사람",
                    ),
                ),
            ],
            options={
                "verbose_name": "쪽지",
                "verbose_name_plural": "쪽지 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
