# Generated by Django 5.2.14 on 2026-05-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="입주민 인증"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="인증일시"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verified_note",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="인증 메모(관리자용)"
            ),
        ),
    ]
