# Generated by Django 5.2.14 on 2026-05-30 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_customuser_is_verified_customuser_verified_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("noise", "소음"),
                            ("parking", "주차"),
                            ("facility", "시설"),
                            ("cleaning", "청소/위생"),
                            ("security", "보안/안전"),
                            ("delivery", "택배"),
                            ("etc", "기타"),
                        ],
                        default="etc",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "접수됨"),
                            ("reviewing", "검토중"),
                            ("done", "처리완료"),
                            ("rejected", "반려"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("admin_reply", models.TextField(blank=True)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "민원/건의",
                "verbose_name_plural": "민원/건의 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("parking", "주차 안내"),
                            ("delivery", "택배 안내"),
                            ("urgent", "긴급 공지"),
                            ("general", "일반 공지"),
                            ("water", "단수/정전"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "빠른 공지",
                "verbose_name_plural": "빠른 공지 목록",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
    ]
