# Generated by Django 5.2.14 on 2026-05-30 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_complaint_notice"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="분류명"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-tag",
                        max_length=30,
                        verbose_name="Bootstrap 아이콘 클래스",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬순서"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "민원 분류",
                "verbose_name_plural": "민원 분류 목록",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="NoticeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="유형명"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-bell",
                        max_length=30,
                        verbose_name="Bootstrap 아이콘 클래스",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="secondary",
                        max_length=20,
                        verbose_name="배지 색상(Bootstrap)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬순서"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
            ],
            options={
                "verbose_name": "공지 유형",
                "verbose_name_plural": "공지 유형 목록",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="complaint",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.complaintcategory",
                verbose_name="분류",
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="notice_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.noticecategory",
                verbose_name="유형",
            ),
        ),
    ]
