# Generated by Django 5.2.14 on 2026-06-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_complaintcategory_noticecategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicchat",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
