# Generated by Django 5.2.14 on 2026-06-02 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_publicchat_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="managementdocument",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AddField(
            model_name="managementdocument",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="docs/", verbose_name="첨부파일"
            ),
        ),
        migrations.AddField(
            model_name="managementdocument",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
        migrations.AlterField(
            model_name="managementdocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("공지", "공지사항"),
                    ("규정", "규정/내규"),
                    ("회의록", "회의록"),
                    ("예산", "예산/결산"),
                    ("계획", "연간계획"),
                    ("기타", "기타"),
                ],
                default="기타",
                max_length=50,
                verbose_name="카테고리",
            ),
        ),
        migrations.AlterField(
            model_name="managementdocument",
            name="content",
            field=models.TextField(blank=True, verbose_name="내용"),
        ),
    ]
