# Generated by Django 5.2.14 on 2026-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_managementdocument_author_managementdocument_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="badges/"),
        ),
    ]
