# Generated by Django 5.2.14 on 2026-06-02 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_badge_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="내용")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("volunteer", "봉사"),
                            ("event", "단지행사"),
                            ("group", "소모임"),
                        ],
                        default="event",
                        max_length=20,
                        verbose_name="종류",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="시작")),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="종료"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="장소"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "전체공개"),
                            ("group", "소모임"),
                            ("pending", "승인대기"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="공개범위",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="승인여부"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="승인일시"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승인자",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to="core.group",
                        verbose_name="소모임",
                    ),
                ),
            ],
            options={
                "verbose_name": "캘린더 일정",
                "verbose_name_plural": "캘린더 일정 목록",
                "ordering": ["start_time"],
            },
        ),
    ]
