# Generated by Django 5.2.14 on 2026-06-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_calendarevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/",
                        verbose_name="히어로 배경사진",
                    ),
                ),
                (
                    "hero_color",
                    models.CharField(
                        default="#1a7a4a", max_length=20, verbose_name="히어로 배경색"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="해솔마을 7단지 지킴이",
                        max_length=100,
                        verbose_name="단지명",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "사이트 설정",
                "verbose_name_plural": "사이트 설정",
            },
        ),
    ]
