# Generated by Django 5.2.14 on 2026-06-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_siteconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="security_answer",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="보안 답변"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="security_question",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="보안 질문"
            ),
        ),
    ]
