# Generated by Django 5.2.14 on 2026-06-02 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_customuser_security_answer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("pw_reset", "비밀번호 초기화"),
                            ("grade_change", "등급 변경"),
                            ("activate", "계정 활성화"),
                            ("deactivate", "계정 비활성화"),
                            ("verify", "입주민 인증 승인"),
                            ("reject", "입주민 인증 거절"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_action_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "관리자 행위 로그",
                "verbose_name_plural": "관리자 행위 로그",
                "ordering": ["-created_at"],
            },
        ),
    ]
