# Generated by Django 5.2.14 on 2026-06-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_adminactionlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["activity_type", "name"],
                "verbose_name": "봉사 활동",
                "verbose_name_plural": "봉사 활동",
            },
        ),
        migrations.AlterModelOptions(
            name="activityproof",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "활동 인증",
                "verbose_name_plural": "활동 인증",
            },
        ),
        migrations.AlterModelOptions(
            name="activityverification",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "활동 검증",
                "verbose_name_plural": "활동 검증",
            },
        ),
        migrations.AlterModelOptions(
            name="badge",
            options={
                "ordering": ["category", "required_points"],
                "verbose_name": "배지",
                "verbose_name_plural": "배지",
            },
        ),
        migrations.AlterModelOptions(
            name="board",
            options={
                "ordering": ["order"],
                "verbose_name": "게시판",
                "verbose_name_plural": "게시판",
            },
        ),
        migrations.AlterModelOptions(
            name="boardgradepermission",
            options={
                "verbose_name": "게시판 등급 권한",
                "verbose_name_plural": "게시판 등급 권한",
            },
        ),
        migrations.AlterModelOptions(
            name="calendarevent",
            options={
                "ordering": ["start_time"],
                "verbose_name": "캘린더 일정",
                "verbose_name_plural": "캘린더 일정",
            },
        ),
        migrations.AlterModelOptions(
            name="chathistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "채팅 기록",
                "verbose_name_plural": "채팅 기록",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글",
            },
        ),
        migrations.AlterModelOptions(
            name="complaint",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "민원/건의",
                "verbose_name_plural": "민원/건의",
            },
        ),
        migrations.AlterModelOptions(
            name="complaintcategory",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "민원 분류",
                "verbose_name_plural": "민원 분류",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "입주민",
                "verbose_name_plural": "입주민",
            },
        ),
        migrations.AlterModelOptions(
            name="directmessage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "1:1 메시지",
                "verbose_name_plural": "1:1 메시지",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "봉사 일정", "verbose_name_plural": "봉사 일정"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "소그룹",
                "verbose_name_plural": "소그룹",
            },
        ),
        migrations.AlterModelOptions(
            name="groupchat",
            options={
                "ordering": ["created_at"],
                "verbose_name": "소모임 채팅",
                "verbose_name_plural": "소모임 채팅",
            },
        ),
        migrations.AlterModelOptions(
            name="groupcomment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "소모임 댓글",
                "verbose_name_plural": "소모임 댓글",
            },
        ),
        migrations.AlterModelOptions(
            name="groupmember",
            options={
                "ordering": ["-joined_at"],
                "verbose_name": "소모임 회원",
                "verbose_name_plural": "소모임 회원",
            },
        ),
        migrations.AlterModelOptions(
            name="grouppost",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "소모임 게시글",
                "verbose_name_plural": "소모임 게시글",
            },
        ),
        migrations.AlterModelOptions(
            name="letter",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "쪽지",
                "verbose_name_plural": "쪽지",
            },
        ),
        migrations.AlterModelOptions(
            name="managementdocument",
            options={
                "ordering": ["category", "title"],
                "verbose_name": "관리 문서",
                "verbose_name_plural": "관리 문서",
            },
        ),
        migrations.AlterModelOptions(
            name="meetup",
            options={
                "ordering": ["scheduled_at"],
                "verbose_name": "번개/모임",
                "verbose_name_plural": "번개/모임",
            },
        ),
        migrations.AlterModelOptions(
            name="membergrade",
            options={
                "ordering": ["order"],
                "verbose_name": "회원 등급",
                "verbose_name_plural": "회원 등급",
            },
        ),
        migrations.AlterModelOptions(
            name="notice",
            options={
                "ordering": ["-is_pinned", "-created_at"],
                "verbose_name": "빠른 공지",
                "verbose_name_plural": "빠른 공지",
            },
        ),
        migrations.AlterModelOptions(
            name="noticecategory",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "공지 유형",
                "verbose_name_plural": "공지 유형",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "알림",
                "verbose_name_plural": "알림",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-is_pinned", "-created_at"],
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글",
            },
        ),
        migrations.AlterModelOptions(
            name="postimage",
            options={
                "ordering": ["order"],
                "verbose_name": "게시글 이미지",
                "verbose_name_plural": "게시글 이미지",
            },
        ),
        migrations.AlterModelOptions(
            name="postlike",
            options={
                "verbose_name": "게시글 좋아요",
                "verbose_name_plural": "게시글 좋아요",
            },
        ),
        migrations.AlterModelOptions(
            name="publicchat",
            options={
                "ordering": ["created_at"],
                "verbose_name": "오픈채팅",
                "verbose_name_plural": "오픈채팅",
            },
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "이웃 온기 평가",
                "verbose_name_plural": "이웃 온기 평가",
            },
        ),
        migrations.AlterModelOptions(
            name="survey",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "설문조사",
                "verbose_name_plural": "설문조사",
            },
        ),
        migrations.AlterModelOptions(
            name="userbadge",
            options={
                "ordering": ["-earned_at"],
                "verbose_name": "회원 보유 배지",
                "verbose_name_plural": "회원 보유 배지",
            },
        ),
    ]
