# Generated by Django 5.2.14 on 2026-06-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_activity_options_alter_activityproof_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicchat",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
