# Generated by Django 5.2.14 on 2026-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_publicchat_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="layout_type",
            field=models.CharField(
                choices=[
                    ("list", "리스트형"),
                    ("gallery", "사진형"),
                    ("card", "사진설명형"),
                    ("market", "중고마켓형"),
                ],
                default="list",
                max_length=20,
                verbose_name="레이아웃",
            ),
        ),
    ]
