# Generated by Django 5.2.14 on 2026-06-03 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_board_layout_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="activity_score",
            field=models.PositiveIntegerField(default=0, verbose_name="활동점수"),
        ),
        migrations.AddField(
            model_name="group",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="승인일시"),
        ),
        migrations.AddField(
            model_name="group",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="승인자",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="dissolve_vote_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="해체투표시작"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="emblem_level",
            field=models.PositiveIntegerField(default=1, verbose_name="엠블럼 레벨"),
        ),
        migrations.AddField(
            model_name="group",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="해체예정일"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="is_limited",
            field=models.BooleanField(default=False, verbose_name="기간한정"),
        ),
        migrations.AddField(
            model_name="group",
            name="join_type",
            field=models.CharField(
                choices=[
                    ("open", "자유가입"),
                    ("approve", "승인제"),
                    ("invite", "초대제"),
                ],
                default="open",
                max_length=20,
                verbose_name="가입방식",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "운영중"),
                    ("pending", "승인대기"),
                    ("dissolving", "해체투표중"),
                    ("dissolved", "해체됨"),
                ],
                default="active",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="ban_reason",
            field=models.TextField(blank=True, verbose_name="퇴장사유"),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="join_status",
            field=models.CharField(
                choices=[
                    ("pending", "가입대기"),
                    ("approved", "승인됨"),
                    ("rejected", "거절됨"),
                    ("banned", "강제퇴장"),
                ],
                default="approved",
                max_length=20,
                verbose_name="가입상태",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_groups",
                through="core.GroupMember",
                through_fields=("group", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="GroupDissolveVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ends_at", models.DateTimeField()),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dissolve_vote",
                        to="core.group",
                    ),
                ),
                (
                    "oppose_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="opposed_dissolves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dissolve_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "해체 투표",
                "verbose_name_plural": "해체 투표",
            },
        ),
        migrations.CreateModel(
            name="GroupLeaderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "소모임 생성"),
                            ("approve", "가입 승인"),
                            ("reject", "가입 거절"),
                            ("ban", "강제 퇴장"),
                            ("invite", "초대"),
                            ("delegate", "방장 위임"),
                            ("dissolve", "해체 신청"),
                            ("edit", "소모임 수정"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leader_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leader_logs",
                        to="core.group",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leader_action_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "방장 활동 기록",
                "verbose_name_plural": "방장 활동 기록",
                "ordering": ["-created_at"],
            },
        ),
    ]
