# Generated by Django 5.2.14 on 2026-06-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_userfollow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "소모임",
                "verbose_name_plural": "소모임",
            },
        ),
    ]
