# Generated by Django 5.2.14 on 2026-06-04 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_group_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarevent",
            options={
                "ordering": ["start_time"],
                "verbose_name": "📅 캘린더 일정",
                "verbose_name_plural": "📅 캘린더 일정",
            },
        ),
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "🤝 소모임",
                "verbose_name_plural": "🤝 소모임",
            },
        ),
        migrations.AlterModelOptions(
            name="groupdissolvevote",
            options={
                "verbose_name": "🤝 해체 투표",
                "verbose_name_plural": "🤝 해체 투표",
            },
        ),
        migrations.AlterModelOptions(
            name="groupleaderlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "🤝 방장 활동 기록",
                "verbose_name_plural": "🤝 방장 활동 기록",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-is_pinned", "-created_at"],
                "verbose_name": "📋 게시글",
                "verbose_name_plural": "📋 게시글",
            },
        ),
        migrations.AlterModelOptions(
            name="survey",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "⚙️ 설문조사",
                "verbose_name_plural": "⚙️ 설문조사",
            },
        ),
        migrations.AlterModelOptions(
            name="userfollow",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "👥 팔로우",
                "verbose_name_plural": "👥 팔로우",
            },
        ),
        migrations.AddField(
            model_name="meetup",
            name="avg_rating",
            field=models.FloatField(default=0.0, verbose_name="평균 평점"),
        ),
        migrations.AddField(
            model_name="meetup",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meetup",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_meetups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meetup",
            name="is_confirmed",
            field=models.BooleanField(default=False, verbose_name="관리자 승인"),
        ),
        migrations.AddField(
            model_name="meetup",
            name="min_participants",
            field=models.IntegerField(default=2, verbose_name="최소 인원"),
        ),
        migrations.AddField(
            model_name="meetup",
            name="rating_count",
            field=models.IntegerField(default=0, verbose_name="평가 수"),
        ),
        migrations.AddField(
            model_name="meetup",
            name="result_note",
            field=models.TextField(blank=True, verbose_name="활동 결과"),
        ),
        migrations.AlterField(
            model_name="meetup",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "계획중"),
                    ("recruiting", "모집중"),
                    ("confirmed", "확정"),
                    ("completed", "완료"),
                    ("cancelled", "취소"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MeetupRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="평점",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="한마디")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meetup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="core.meetup",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetup_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "봉사활동 평가",
                "verbose_name_plural": "봉사활동 평가",
                "unique_together": {("meetup", "rater")},
            },
        ),
    ]
