# Generated by Django 5.2.14 on 2026-06-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_calendarevent_options_alter_group_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "개인"),
                    ("group", "소모임"),
                    ("public", "전체공개"),
                    ("pending", "승인대기"),
                ],
                default="pending",
                max_length=20,
                verbose_name="공개범위",
            ),
        ),
    ]
