# Generated by Django 5.2.14 on 2026-06-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_calendarevent_options_alter_group_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
