# Generated by Django 5.2.14 on 2026-06-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_alter_calendarevent_visibility"),
        ("core", "0034_notification_link"),
    ]

    operations = []
