# Generated by Django 5.2.14 on 2026-06-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_merge_20260604_1649"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trade",
            options={"verbose_name": "거래 정보", "verbose_name_plural": "거래 정보"},
        ),
        migrations.AddField(
            model_name="trade",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "가전/디지털"),
                    ("furniture", "가구/인테리어"),
                    ("clothing", "의류/패션"),
                    ("food", "식품/음료"),
                    ("living", "생활용품"),
                    ("books", "도서/문구"),
                    ("sports", "스포츠/레저"),
                    ("kids", "유아/아동"),
                    ("plants", "식물/원예"),
                    ("etc", "기타"),
                ],
                default="etc",
                max_length=30,
                verbose_name="카테고리",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "새상품"),
                    ("like_new", "거의 새것"),
                    ("good", "상태 좋음"),
                    ("normal", "보통"),
                    ("bad", "나쁨"),
                ],
                default="good",
                max_length=20,
                verbose_name="상품상태",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="delivery",
            field=models.CharField(
                choices=[
                    ("direct", "직거래"),
                    ("delivery", "택배"),
                    ("both", "직거래+택배"),
                ],
                default="direct",
                max_length=20,
                verbose_name="거래방법",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="is_negotiable",
            field=models.BooleanField(default=True, verbose_name="가격협의"),
        ),
        migrations.AddField(
            model_name="trade",
            name="trade_location",
            field=models.CharField(
                blank=True, default="단지 내", max_length=100, verbose_name="거래장소"
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(
                choices=[("sell", "판매"), ("share", "나눔"), ("exchange", "교환")],
                default="sell",
                max_length=20,
                verbose_name="거래유형",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="groupleaderlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "소모임 생성"),
                    ("approve", "가입 승인"),
                    ("reject", "가입 거절"),
                    ("ban", "강제 퇴장"),
                    ("invite", "초대"),
                    ("delegate", "방장 위임"),
                    ("dissolve", "해체 신청"),
                    ("edit", "소모임 수정"),
                    ("admin_change", "관리자 변경"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="join_status",
            field=models.CharField(
                choices=[
                    ("pending", "가입대기"),
                    ("invited", "초대됨"),
                    ("approved", "승인됨"),
                    ("rejected", "거절됨"),
                    ("banned", "강제퇴장"),
                ],
                default="approved",
                max_length=20,
                verbose_name="가입상태",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="가격"
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "판매중/나눔중"),
                    ("reserved", "예약중"),
                    ("sold", "거래완료"),
                ],
                default="available",
                max_length=20,
                verbose_name="거래상태",
            ),
        ),
    ]
