# Generated by Django 5.2.14 on 2026-06-06 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_trade_options_trade_category_trade_condition_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={
                "verbose_name": "설문조사",
                "verbose_name_plural": "설문조사 목록",
            },
        ),
        migrations.AddField(
            model_name="poll",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_polls",
                to="core.group",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polls",
                to="core.post",
            ),
        ),
    ]
