# Generated by Django 5.1.3 on 2026-06-06 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_poll_group_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="is_recurring",
            field=models.BooleanField(default=False, verbose_name="반복여부"),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recur_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="반복종료일"),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recur_interval",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="반복간격"),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recur_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recur_children",
                to="core.calendarevent",
                verbose_name="원본일정",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recur_type",
            field=models.CharField(
                choices=[
                    ("none", "없음"),
                    ("daily", "매일"),
                    ("weekly", "매주"),
                    ("monthly", "매월"),
                ],
                default="none",
                max_length=10,
                verbose_name="반복종류",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("personal", "개인"),
                    ("volunteer", "봉사"),
                    ("event", "단지행사"),
                    ("group", "소모임"),
                ],
                default="event",
                max_length=20,
                verbose_name="종류",
            ),
        ),
    ]
