# Generated by Django 5.2.14 on 2026-06-07 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_calendarevent_is_recurring_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarevent",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="recur_end_date",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="recur_parent",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="recur_type",
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="group_approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="소모임장승인일시"
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="group_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_approved_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="소모임장승인자",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="rrule",
            field=models.TextField(blank=True, verbose_name="반복규칙(RRule)"),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="관리자승인"),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "나만보기"),
                    ("group_pending", "소모임공개(승인대기)"),
                    ("group", "소모임공개"),
                    ("pending", "전체공개(승인대기)"),
                    ("public", "전체공개"),
                ],
                default="private",
                max_length=20,
                verbose_name="공개범위",
            ),
        ),
    ]
