# Generated by Django 5.2.14 on 2026-06-07 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_remove_calendarevent_is_recurring_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="all_day",
            field=models.BooleanField(default=False, verbose_name="종일여부"),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="color",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="색상"
            ),
        ),
        migrations.CreateModel(
            name="CalendarEventComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.calendarevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "일정 댓글",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEventAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("attending", "참석"),
                            ("declined", "불참"),
                            ("maybe", "미정"),
                        ],
                        default="attending",
                        max_length=20,
                        verbose_name="참석여부",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="core.calendarevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "일정 참석자",
                "unique_together": {("event", "user")},
            },
        ),
    ]
