# Generated by Django 5.2.14 on 2026-06-09 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_calendarevent_all_day_calendarevent_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="위치"),
        ),
        migrations.CreateModel(
            name="ComplaintImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="complaints/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.complaint",
                    ),
                ),
            ],
            options={
                "verbose_name": "민원 이미지",
                "verbose_name_plural": "민원 이미지",
            },
        ),
    ]
